### ISSUE TITLE
CSV Encoding

### ISSUE THREAD

**Issue by jsoulier** [gabrielmartell/COMP3005-Project-Template#10]
Could you modify the write_csv function in the autograder with the following:

```python
# with open(filename, 'w', newline='') as csvfile:
with open(filename, 'w', encoding='utf-8', newline='') as csvfile:
```

The default for me is not utf-8. Without the change I was getting errors for all non-ascii names.

Thanks

**Comment by gabrielmartell** [comment]
Hi @jsoulier,

Yes.

Thanks,
Gabe
