### ISSUE TITLE
GitHub submission format & other questions

### ISSUE THREAD

**Issue by JoeyVilleneuve** [gabrielmartell/COMP3005-Project-Template#11]
Hi there,
Just wanted to clarify a few things.

1. My .SQL file is larger than GitHub's maximum 100mb single file limit so I had to compress it. Can I assume that the TA will unzip it before running the autograder?
2. The README states that any other files in our submission other than queries.py, dbexport.SQL, and the json_loader folder with our database creation script inside will void the entire submission. But we also need to submit a project report PDF and diagram image files for the project. Are we just intended to put our code-related files in a sub-folder in our repo or something?
3. Does queries.py judge query correctness? It gives us runtimes but I'm not sure if the speeds are actually good or if the queries are returning as expected.

Thanks for your time,
Joey V.

**Comment by JoeyVilleneuve** [comment]
Oh and 
4. My project_database creation script uses a filepath to the StatsBomb data folder's location on the user's device. Is there some filepath that I should set it to ahead of time so the autograder doesn't throw a fit?

**Comment by gabrielmartell** [comment]
Hi @JoeyVilleneuve,

1. I did update the README and general submission requirements to do this - if you compress the file into a Git LFS that should do the trick. You import it as an LFS file, and then the autograder exports it back to a regular file. (With this in mind, the files submitted should be the queries.py, dbexport.sql, json_loader and ".gitattributes", where .gitattributes is created when you import the file as an LFS). Do not fret though, I do have a step-by-step on how to do it in the README so you shouldn't need to figure it out yourself.

2. The repository submission is code only - the report is submitted via. Brightspace.

3. The queries.py file only does runtime, not correctness.

4. You may leave it as is - the autograder doesn't touch the json_loader.

**Comment by JoeyVilleneuve** [comment]
Perfect, thanks!

**Comment by gabrielmartell** [comment]
No problem, feel free to put up another issue if you run into any other issues!
However I must admit that I too am becoming burdened by other class and pesky assignments so my responses may be delayed longer than usual.

Good Luck,
Gabe
