### ISSUE TITLE
Can't Push From Remote

### ISSUE THREAD

**Issue by JoeyVilleneuve** [gabrielmartell/COMP3005-Project-Template#12]
Hi there,
I have been attempting to push to main via the Ubuntu remote using "git push -u origin main" as instructed but nothing happens. The "git status" command returns everything correctly and I know the key token I'm using is right because I can pull just fine. However, "git push -u origin main" just returns nothing, then immediately prompts me for my user/password again in an infinite loop. Any ideas?

Thanks,
Joey V.

**Comment by gabrielmartell** [comment]
Hi @JoeyVilleneuve 

This also happened to me when testing this, my resolve? 
My username and/or password was wrong.

What I dislike about entering passwords in the Linux terminal is that it doesn't show anything - so you don't know if your password paste was actually successful or not. My fix was, If you put your username again, and copy your token, **_don't Ctrl + V_**, instead, right click on the terminal line and then paste. 

This is, of course, assuming you didn't do this already.

Let me know if this was the case,

Thanks!
Gabe

**Comment by JoeyVilleneuve** [comment]
Hi Gabe,
Unfortunately I have typed out my code manually and using right click -> paste multiple times, and it refuses to work. I know the password is correct because it doesn't kick me out, unlike when I enter a wrong password.

**Comment by gabrielmartell** [comment]
Strange...

Can you try, which I got from this [article](https://medium.com/illumination/how-to-use-username-and-password-to-push-commits-on-github-39f184bbafc1):
```git push -u https://<username>:<access_token>@<remote-url-without-https> main```

**Comment by gabrielmartell** [comment]
After reading some issues on git lfs, apparently getting the remote from the SSH link instead of the HTTPS link caused problems too... did you perhaps do this?

**Comment by JoeyVilleneuve** [comment]
Just tried those, no dice. I've tried both the HTTPS and SSH formatting for the remote link, again I get through but it won't push, only pull. I also just tried the entire process from scratch in another class VM, same thing. I even changed the workflow rules in the repo to read/write as per a suggestion online, nothing.

**Comment by JoeyVilleneuve** [comment]
![Screenshot_743](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/61750766/daffdf94-70b9-43da-96ea-df85f797043c)

**Comment by gabrielmartell** [comment]
I'm primarily looking at this raised [issue](https://github.com/git-lfs/git-lfs/issues/203) from the Git LFS issues tab. Apparently it loops twice per one file. I'd hate to suggest this (since its very silly) but I'd say to just keep on putting your username and password. I'll look into Git Credentials tomorrow (something someone commented in this issue I linked).

**Comment by JoeyVilleneuve** [comment]
.....I finally found it. It turns out, the loop isn't endless. I just needed to login for **every** single file. Now its going through. Phew! What a headache.

**Comment by JoeyVilleneuve** [comment]
Oop we just found the same answer at the same time haha

**Comment by gabrielmartell** [comment]
Lol
I'll make sure to update the README
