### ISSUE TITLE
queries.py: System environment varaibles not imported to the subprocess.run(), psql is not a recognized command

### ISSUE THREAD

**Issue by ZoltanBiro** [gabrielmartell/COMP3005-Project-Template#13]
When running queries.py I was getting the error: "'psql' is not recognized as an internal or external command, operable program or batch file.". I believe this is because the environment variables were not being used while initializing the subprocess.

To solve this issue, I've change the code from:
>env = {'PGPASSWORD': password}
subprocess.run(command, shell=True, check=True, env=env)

To:
>env = os.environ.copy()
        env['PGPASSWORD'] = password
subprocess.run(command, shell=True, check=True, env=env)

This resolves this issue on my machine.

**Comment by gabrielmartell** [comment]
Hi @ZoltanBiro,

Are you using a Linux environment?

**Comment by ZoltanBiro** [comment]
no
