### ISSUE TITLE
[ERROR] Error Getting Time

### ISSUE THREAD

**Issue by stevenkong24** [gabrielmartell/COMP3005-Project-Template#15]
Hi Gabriel,

I've been stuck on the following error for a little bit and had a question. After running queries.py, I get the following:
![image_2024-04-11_140712411](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/99783492/45234097-af55-4855-a2bb-9c8f9f9cf336)
This error message is vague I was wondering if it were acceptable to add a line of code to print the exception in the except block in get_time(). This is only so I can debug why I can't get the autograder to work, and wanted to ask before making any changes because of the Academic Integrity policy. If not, it would be great if you had an idea what would be causing this, however I'm assuming it is something within my code.

Thanks,
Steven

**Comment by gabrielmartell** [comment]
Hi @stevenkong24,

I updated the queries code to be more precise on why getting the time is crashing. But, most usually, it is because of a syntax error or typo within your query. You are always free to edit the code, but it should be in its initial state when submitted. 

Thanks,
Gabe

**Comment by stevenkong24** [comment]
Fantastic thank you! That solved that issue, as I found the error within my query. It was able to successfully run the autograder, however once I try to run it a second time, I get the following:

![image_2024-04-11_163910756](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/99783492/74b8164d-1b18-4250-9665-b98778983171)

I've researched this and seen people suggesting to edit .conf files in /etc/postgresql/main however I cannot do this since they are read only. Would you happen to know what could be causing this? Just confused as it ran the first time, however I receive this error upon a second attempt

**Comment by gabrielmartell** [comment]
Hm, I'm not too sure...
If it ran the first time but not the second time, my only guess would be that maybe you accidentally changed the name of one of the connection properties between the two. Ensure that the values here...
```
root_database_name = "project_database"
query_database_name = "query_database"
db_username = 'postgres'
db_password = '1234'
db_host = 'localhost'
db_port = '5432'
```
... or however you named it, match the ones of your actual psql settings.

**Comment by gabrielmartell** [comment]
Assuming this is solved, I am going to close this issue.
Please open up another if you have questions!

Thanks!
Gabe
