### ISSUE TITLE
Error occurs when referencing path to dbexport.sql 

### ISSUE THREAD

**Issue by JackieSL1** [gabrielmartell/COMP3005-Project-Template#16]
I'm running into errors when `dbexport.sql` is ran by the script because my project path has parenthesis in it. Would you be able to add quotes around the path to avoid this?

```python
# BEFORE
command = f'psql -h {host} -U {user} -d {query_database_name} -a -f {os.path.join(dir_path, "dbexport.sql")}'

# AFTER
command = f'psql -h {host} -U {user} -d {query_database_name} -a -f \'{os.path.join(dir_path, "dbexport.sql")}\''
```

Thanks!

**Comment by gabrielmartell** [comment]
Hi @JackieSL1,
I'm a bit confused by this - dir_path is the current directory in which queries.py is in - dbexport.sql should be in the same directory.

**Comment by JackieSL1** [comment]
queries.py and db.export.sql are both in the same directory. I think the problem is that the path of my project directory has spaces in it which is causing this error message:

> ➜  comp-3005-project git:(main) ✗ python3 queries.py
psql: warning: extra command-line argument "-" ignored
psql: warning: extra command-line argument "Local/2024" ignored
psql: warning: extra command-line argument "Winter" ignored
psql: warning: extra command-line argument "-" ignored
psql: warning: extra command-line argument "Local/COMP" ignored
psql: warning: extra command-line argument "3005/Project/comp-3005-project/dbexport.sql" ignored
psql: error: /mnt/c/Users/jacki/School: No such file or directory
An error occurred while loading the database: Command 'psql -h localhost -U postgres -d query_database -a -f /mnt/c/Users/jacki/School - Local/2024 Winter - Local/COMP 3005/Project/comp-3005-project/dbexport.sql' returned non-zero exit status 1.
[ERROR] Error getting time.
relation "competitions" does not exist
LINE 2: ...ect player_name, avg(statsbomb_xg) as avg_xg from competitio...
                                                             ^
current transaction is aborted, commands ignored until end of transaction block

Here my project path is `/mnt/c/Users/jacki/School - Local/2024 Winter - Local/COMP 3005/Project/comp-3005-project/dbexport.sql`

**Comment by gabrielmartell** [comment]
I see,

You are right, the error is because your directory does have spaces.

I'll do the changes when I push the final update regarding the reported issues - but given the timeframe and assuming you want this completed, it might be better for you to work in a directory that doesn't include spaces temporarily as this potential final update requires my full attention.

Thanks,
Gabe
