### ISSUE TITLE
Database fails to be deleted due to dead connection

### ISSUE THREAD

**Issue by csjh** [gabrielmartell/COMP3005-Project-Template#17]
Line 45 of `queries.py` forwards `cursor` and `conn` to `drop_database`. However, the cursor that's passed in is the same one that's initialized in the top level `__name__ == "__main__"`. Its corresponding `conn` is closed on line 56 of `queries.py`. This leads to any follow-up usages of `cursor` (i.e., on the next attempt to drop & create the database) to fail with the error 'the connection is closed'.

I can PR a fixed copy if you'd like but it should be as simple as localizing the connection and cursor to the function where it's used.

**Comment by gabrielmartell** [comment]
Bless you @csjh,

Your suggestion just solved the bug brooding over me since last night. 👍 
Thanks for catching my incredibly messy connection logic.

Gabe
