### ISSUE TITLE
im getting the error "connection failure: Connection refused Is the server running on that host and accepting TCP/IP connections?"

### ISSUE THREAD

**Issue by ney927** [gabrielmartell/COMP3005-Project-Template#18]
Hi, 
I posted this question in the Q&A but read that I should ask queries.py relation questions here. 
Basically, I was able to insert data into the project_database we created using psycopg2 

However, I am now trying to run the queries.py file in a virtual Linux environment to test my queries and receiving the following error:

connection failure: Connection refused Is the server running on that host and accepting TCP/IP connections?

I have not changed any of the code except for entering the queries in their respective locations, and the name of our database is project_database. Also, I have not been able to change the password for the user 'postgres' to '1234' so i have tried changing the db_password value to my password for testing purposes.

**Comment by gabrielmartell** [comment]
Hi @ney927,

Try using the following code snippet: `sudo service postgresql restart` - this should solve your connection issue.

To change the password of postgres, in the terminal do the following snippets of code:
- `sudo -u postgres psql`
- `\password postgres`
- Enter the password `1234`

Thanks,
Gabe

**Comment by ney927** [comment]
Hi Gabe,

Unforunately running 'sudo service postgresql restart' gives me this error: 

Failed to restart postgresql.service: Unit postgresql.service not found.

Thanks,
Neyha
