### ISSUE TITLE
Benchmarking queries internally to PSQL instead of through psycopg

### ISSUE THREAD

**Issue by csjh** [gabrielmartell/COMP3005-Project-Template#2]
Hi, would it be possible to switch the benchmark from just wrapping the single psycopg execution in `time.time()` to using an in-SQL benchmark? The one I've been using for tests is:

```sql
CREATE OR REPLACE FUNCTION bench(query TEXT, iterations INTEGER = 500)
RETURNS TABLE(median FLOAT) AS $$
DECLARE
  _start TIMESTAMPTZ;
  _end TIMESTAMPTZ;
  _delta DOUBLE PRECISION;
BEGIN
  CREATE TEMP TABLE IF NOT EXISTS _bench_results (
      elapsed DOUBLE PRECISION
  );

  -- Warm the cache
  FOR i IN 1..5 LOOP
    EXECUTE query;
  END LOOP;

  -- Run test and collect elapsed time into _bench_results table
  FOR i IN 1..iterations LOOP
    _start = clock_timestamp();
    EXECUTE query;
    _end = clock_timestamp();
    _delta = 1000 * ( extract(epoch from _end) - extract(epoch from _start) );
    INSERT INTO _bench_results VALUES (_delta);
  END LOOP;

  RETURN QUERY SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY elapsed) FROM _bench_results;
  DROP TABLE IF EXISTS _bench_results;

END
$$
LANGUAGE plpgsql;
```
then executing with:
```python
cursor.execute(f"SELECT median FROM bench(%s)", (query,))
result = cursor.fetchone()
print(f"Query #{str(i).zfill(2)} took {round(result[0], 2)}ms")
```

The benefit is that one execution time spiking because of some Python performance annoyance isn't possible, because the execution time is derived from multiple executions from within the SQL engine.

Then for the actual query correctness results the regular execution can still be done and written to a CSV

**Comment by gabrielmartell** [comment]
Hi @csjh,

The autograder does not run the queries once and take the execution times then and there; the autograder does not do a single run with a submission. Instead, the autograder does multiple runs of the queries and calculates an average execution time (similar to your tester code snippet).

I understand your concern and worries, but I can assure you that all submissions, including yours, will not be negatively affected by any outlier values. 

I will close this issue, **but please feel free to create a new one if you continue to have concerns.**
