### ISSUE TITLE
duplicating values with each query

### ISSUE THREAD

**Issue by owen-petersen** [gabrielmartell/COMP3005-Project-Template#20]
Seems like when the queries are being ran some of the values in the database are being duplicated. When looking at the outputs in the csv files for each query and comparing it to the tables produced when I run the queries in pgadmin4 on my own test database (which I set up with the same dbexport.sql dump file) the values are multiplied by the query number. For example, the values in Q_2.csv are twice the value compared to the output in pgadmin4 on my test database. The values in Q_3.csv are three times the value compared to the output in my test databse. The values in Q_4.csv are four times the value compared to my test database. I assume that this might be an error somewhere in the queries.py file so I wanted to mention it.

**Comment by gabrielmartell** [comment]
Hi @owen-petersen,

This was actually brought to my and Ahmed's attention a few days ago.
As of 10:39am EST today, I **just** fixed it (hopefully). I'll push changes ASAP today - I just need to finalize, test, clean up... yada yada...

Thanks!
Gabe
