### ISSUE TITLE
Error Running Queries with no explanation

### ISSUE THREAD

**Issue by Fail-staff** [gabrielmartell/COMP3005-Project-Template#7]
Dear Gabriel.

Having an issue running query number 1.  When I run the queries on the created database using PGAdmin it works absolutely no problem. No errors, no warnings.

The moment I insert the query into the queries.py file, it tells me that the "match" table does not exist. This is impossible as it exists in the DB, and I ran the queries in PgAdmin with no issue as described before.

The DB name is project_database, as was instructed, and I am running the code on a VM with Ubuntu, everything else is working.

Not sure what to do here, is there a step I am missing? I have inserted my query directly into the string for the query in queries.py.

Please any help would be appreciated, I am very confused, again the query functions fine in PgAdmin

**Comment by gabrielmartell** [comment]
Hi @Fail-staff,

The code takes your dbexport.sql and creates a new database where it will run its queries. If you are getting an error where a _specific table_ does not exist, it could mean that your JSON data that you imported into your database (dbexport.sql) is wrong. Or, this could mean that your dbexport.sql isn't updated with the database you are currently testing on in pgAdmin 4.

Please let me know if you have any other issues!
Gabe

**Comment by Fail-staff** [comment]
> Hi @Fail-staff,
> 
> The code takes your dbexport.sql and creates a new database where it will run its queries. If you are getting an error where a _specific table_ does not exist, it could mean that your JSON data that you imported into your database (dbexport.sql) is wrong. Or, this could mean that your dbexport.sql isn't updated with the database you are currently testing on in pgAdmin 4.
> 
> Please let me know if you have any other issues! Gabe

Ok but I know this data isnt wrong and I know that the table exists. 

The table we are testing on is created using our script, how would be fix a dbexport.sql file issue? Where would I even find that file

**Comment by Fail-staff** [comment]
> Hi @Fail-staff,
> 
> The code takes your dbexport.sql and creates a new database where it will run its queries. If you are getting an error where a _specific table_ does not exist, it could mean that your JSON data that you imported into your database (dbexport.sql) is wrong. Or, this could mean that your dbexport.sql isn't updated with the database you are currently testing on in pgAdmin 4.
> 
> Please let me know if you have any other issues! Gabe

Upon further inspection, I have noticed that the dbexport.sql file creates its OWN tables from OUR DB?

where the table "matches" exists. however our table in our DB that we created is called "match". Does "match" get automatically mapped to "matches"? I am insanely confused about the system here.

Are our tables unaltered or does the dbexport.sql file alter them and their properties? Do I need to work with the new names?

**Comment by gabrielmartell** [comment]
The dbexport.sql file in this repository is simply a **tester** for both the students and myself - it is _not_ used and **shouldn't** be used for your submission.
As per the project guidlines:

> "Design a database that stores a soccer events dataset spanning multiple competitions and seasons. The provided
dataset is in JSON format and can be downloaded from https://github.com/statsbomb/open-data/tree/0067cae166a56aa80b2ef18f61e16158d6a7359a1. The documentation of the dataset is also available in the
above URL. After designing the database, you need to import the data from the JSON files into your database."

Assuming you do this, create your database, and then export the database into your dbexport.sql, you shouldn't run into any issues. This data has the correct use of table "matches" because the data in this JSON here is categorized as "matches", not "match".

Please let me know if you have any other questions!
Gabe

**Comment by Fail-staff** [comment]
I dont understand, are we supposed to run the autograder with our created database? It wont recognize the tables but it works in PgAdmin? There must be something I am missing here

I ran a script to create the database.

Then a ran the autograder with my query.

Is there a step that I missed?

**Comment by gabrielmartell** [comment]
What your steps should be are:

- With this JSON dataset, export that data to create a database.
- Export that database into a dbexport.sql file
- Run your queries inside the queries.py, as this script uses that dbexport.sql

When you export the JSON dataset, the named directories in the data directory should be retained. As in your case - there should be a "matches" table, not a table named "match".
Is this what you did?

**Comment by Fail-staff** [comment]
ahh I see that makes sense! It seems that our dbexport.sql is for some reason creating a different version of the database. I appreciate all the help, I apologize for my frantic tone. Thank you so much
